### PR TITLE
fixes #1: Filenames of 13/26/39/etc. characters get scrambled

### LINKED ISSUE #1: Filenames of exactly 26 characters get scrambled
I'm using packer to build a floppy with a file named `enable-quick-edit-mode.cmd`. The resultant floppy image's filename appears corrupted in Windows (under VMWare), in IsoBuster, and when I mount the image using ImDisk Virtual Disk Driver for Windows.

When I rename the file to be 25 or 27 characters, the corruption disappears. 

Here's a screenshot of the corruption in IsoBuster:
screenshot - 11_14_13 11_04_56 am

Here's another screenshot that shows only files of exactly 26 characters are affected:
screenshot - 11_14_13 2_34_14 pm

### PR DESCRIPTION
**Pull request by rasa**

### CODE REVIEW

**Comment by rasa** [comment]
I forgot to mention the bug only appears if the filename has an extension.

**Comment by rasa** [comment]
Also, it looks like it's happening for files of 13, 26, 39, ... characters in length. Here's a screen shot:
screenshot - 11_17_13 11_26_09 am

**Comment by mitchellh** [comment]
Thanks! Yeah, these issues are usually in the shortname generation:

https://github.com/mitchellh/go-fs/blob/master/fat/short_name.go

Or perhaps in the FAT header.... ugh.

(They're the worst)

**Comment by rasa** [comment]
I'm seeing a couple of different commits in template repos that workaround this issue by renaming files. For example:
https://github.com/misheska/basebox-packer/commit/d292fda8124c7742089557106160bb2f77ebc518#commitcomment-4984199

Also, https://github.com/mitchellh/packer/issues/285 appears to be the same issue, as the file was 13 characters long, so I don't think that https://github.com/mitchellh/go-fs/commit/290bdc8ba6c67ab72fa2e29fbaec7776bf344378 fixed it.

**Comment by mitchellh** [comment]
Thanks for the fix! I'll take it :)

**Comment by rasa** [comment]
SwaEET!

**Pull request merged**
